import { createServerFn } from "@tanstack/react-start";

type Result = { url: string | null; error?: string };

const BUCKET = "narrations";
const KALIMA_MAX_LEN = 300;
// Daniel — warm, measured male voice. Renders Arabic dhikr with a calmer,
// more melodic delivery than Adam via the multilingual model.
const KALIMA_VOICE_ID = "onwK4e9ZLuTAKqWW03F9";
// Bump when voice or voice_settings change, so we don't serve stale audio
// generated by the previous voice from the storage cache.
const KALIMA_VOICE_REV = "v2-daniel";

async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const buf = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// Public — Arabic TTS for short kalimas/dhikr. Cached by sha256 of the text so
// repeat callers always hit storage. No auth required: input is a bounded
// Arabic string and the cost is one-time per unique kalima.
export const getKalimaAudio = createServerFn({ method: "POST" })
  .inputValidator((data: { text: string }) => {
    if (!data || typeof data.text !== "string") throw new Error("invalid_text");
    const text = data.text.trim();
    if (!text || text.length > KALIMA_MAX_LEN) throw new Error("invalid_length");
    return { text };
  })
  .handler(async ({ data }): Promise<Result> => {
    try {
      const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

      const key = await sha256Hex(data.text);
      const path = `kalimas/${key}.mp3`;

      const { data: existing } = await supabaseAdmin.storage.from(BUCKET).list("kalimas", {
        search: `${key}.mp3`,
        limit: 1,
      });
      if (existing && existing.length > 0) {
        const { data: pub } = supabaseAdmin.storage.from(BUCKET).getPublicUrl(path);
        return { url: pub.publicUrl };
      }

      const apiKey = process.env.ELEVENLABS_API_KEY;
      if (!apiKey) return { url: null, error: "missing_api_key" };

      const res = await fetch(
        `https://api.elevenlabs.io/v1/text-to-speech/${KALIMA_VOICE_ID}?output_format=mp3_44100_128`,
        {
          method: "POST",
          headers: { "xi-api-key": apiKey, "Content-Type": "application/json" },
          body: JSON.stringify({
            text: data.text,
            model_id: "eleven_multilingual_v2",
            voice_settings: {
              stability: 0.6,
              similarity_boost: 0.8,
              style: 0.2,
              use_speaker_boost: true,
              speed: 0.9,
            },
          }),
        },
      );
      if (!res.ok) {
        const errText = await res.text();
        console.error("[tts:kalima] elevenlabs error", res.status, errText);
        return { url: null, error: `elevenlabs_${res.status}` };
      }
      const audio = new Uint8Array(await res.arrayBuffer());

      const { error: upErr } = await supabaseAdmin.storage
        .from(BUCKET)
        .upload(path, audio, { contentType: "audio/mpeg", upsert: true });
      if (upErr) {
        console.error("[tts:kalima] upload failed", upErr);
        return { url: null, error: "upload_failed" };
      }

      const { data: pub } = supabaseAdmin.storage.from(BUCKET).getPublicUrl(path);
      return { url: pub.publicUrl };
    } catch (e) {
      console.error("[tts:kalima] generate failed", e);
      return { url: null, error: "unexpected" };
    }
  });
