export const KALIMA_TTS_BUCKET = "narrations";
export const KALIMA_MAX_LEN = 300;

// Brian — warm, calm, melodious male voice. Renders Arabic dhikr with a
// gentle, meditative delivery via the multilingual model.
export const KALIMA_VOICE_ID = "nPczCjzI2devNBz1zQrb";
// Bump when voice or voice_settings change, so we don't serve stale audio
// generated by the previous voice from the storage cache.
export const KALIMA_VOICE_REV = "v8-brian";

export const KALIMA_VOICE_SETTINGS = {
  stability: 0.75,
  similarity_boost: 0.85,
  style: 0.35,
  use_speaker_boost: true,
  speed: 0.85,
};

export async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const buf = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export function isValidKalimaText(text: string) {
  const trimmed = text.trim();
  return trimmed.length > 0 && trimmed.length <= KALIMA_MAX_LEN;
}

export function kalimaAudioPath(hash: string) {
  return `kalimas/${hash}.mp3`;
}

export async function kalimaCacheHash(text: string) {
  return sha256Hex(`${KALIMA_VOICE_REV}:${text}`);
}

export function kalimaAudioEndpoint(hash: string, text?: string) {
  const base = `/api/public/kalima-tts/${hash}`;
  return text ? `${base}?text=${encodeURIComponent(text)}` : base;
}