/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnimateRouteImport } from './routes/animate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurahNumberRouteImport } from './routes/surah.$number'
import { Route as MoodIdRouteImport } from './routes/mood.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimateRoute = AnimateRouteImport.update({
  id: '/animate',
  path: '/animate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahNumberRoute = SurahNumberRouteImport.update({
  id: '/surah/$number',
  path: '/surah/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodIdRoute = MoodIdRouteImport.update({
  id: '/mood/$id',
  path: '/mood/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animate': typeof AnimateRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/mood/$id': typeof MoodIdRoute
  '/surah/$number': typeof SurahNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animate': typeof AnimateRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/mood/$id': typeof MoodIdRoute
  '/surah/$number': typeof SurahNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animate': typeof AnimateRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/mood/$id': typeof MoodIdRoute
  '/surah/$number': typeof SurahNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animate'
    | '/auth'
    | '/settings'
    | '/mood/$id'
    | '/surah/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animate' | '/auth' | '/settings' | '/mood/$id' | '/surah/$number'
  id:
    | '__root__'
    | '/'
    | '/animate'
    | '/auth'
    | '/settings'
    | '/mood/$id'
    | '/surah/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimateRoute: typeof AnimateRoute
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRoute
  MoodIdRoute: typeof MoodIdRoute
  SurahNumberRoute: typeof SurahNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animate': {
      id: '/animate'
      path: '/animate'
      fullPath: '/animate'
      preLoaderRoute: typeof AnimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$number': {
      id: '/surah/$number'
      path: '/surah/$number'
      fullPath: '/surah/$number'
      preLoaderRoute: typeof SurahNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/$id': {
      id: '/mood/$id'
      path: '/mood/$id'
      fullPath: '/mood/$id'
      preLoaderRoute: typeof MoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimateRoute: AnimateRoute,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRoute,
  MoodIdRoute: MoodIdRoute,
  SurahNumberRoute: SurahNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
